language: c
dist: trusty

env:
  global:
    - MAKEFLAGS="-j2"
    - LIBACARS_BRANCH="master"
    - VDL2_TEST1="--iq-file ../test/vdl2_model_16b_1050kHz.wav --sample-format S16_LE --extended-header"
    - VDL2_TEST1_EXPECT="20 2d 52 41 20 42 52 20 4f 56 43 30 30 35 0a|20 53 4c 50 31 33 35 0a"
    - VDL2_TEST1_RESULT=2

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    update: true
    packages:
    - libglib2.0-dev
    - pkg-config
    - librtlsdr-dev
  homebrew:
    packages:
    - glib

install:
  # libacars
  - git clone https://github.com/szpajder/libacars.git
  - pushd libacars
  - git checkout ${LIBACARS_BRANCH}
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - sudo ldconfig
  - popd

script:
  - mkdir build
  - cd build
  - cmake ../
  - make VERBOSE=1
  - sudo make install
  - dumpvdl2 ${VDL2_TEST1}
  - res=`dumpvdl2 ${VDL2_TEST1} | egrep -c "${VDL2_TEST1_EXPECT}"`
  - if [[ "x$res" = "x" ]]; then false; fi
  - if [[ $res -eq ${VDL2_TEST1_RESULT} ]]; then true; fi
